
// Do not edit directly
// Generated on Thu, 21 Nov 2024 12:15:53 GMT

export const spTokenTypes = [
"color_primitive_amber_30",
"color_primitive_amber_50",
"color_primitive_bamboo_30",
"color_primitive_bamboo_50",
"color_primitive_blue_10",
"color_primitive_blue_100",
"color_primitive_blue_15",
"color_primitive_blue_20",
"color_primitive_blue_30",
"color_primitive_blue_50",
"color_primitive_blue_60",
"color_primitive_blue_90",
"color_primitive_brown_30",
"color_primitive_brown_50",
"color_primitive_cork_100",
"color_primitive_cork_30",
"color_primitive_cork_50",
"color_primitive_cork_60",
"color_primitive_emerald_30",
"color_primitive_emerald_50",
"color_primitive_green_10",
"color_primitive_green_100",
"color_primitive_green_130",
"color_primitive_green_30",
"color_primitive_green_40",
"color_primitive_green_50",
"color_primitive_leaf_30",
"color_primitive_leaf_50",
"color_primitive_lemon_30",
"color_primitive_lemon_50",
"color_primitive_lime_100",
"color_primitive_lime_30",
"color_primitive_lime_50",
"color_primitive_lime_60",
"color_primitive_marine_10",
"color_primitive_marine_100",
"color_primitive_marine_130",
"color_primitive_marine_30",
"color_primitive_marine_40",
"color_primitive_marine_50",
"color_primitive_marine_60",
"color_primitive_neutral_10",
"color_primitive_neutral_100",
"color_primitive_neutral_20",
"color_primitive_neutral_30",
"color_primitive_neutral_40",
"color_primitive_neutral_50",
"color_primitive_neutral_70",
"color_primitive_neutral_80",
"color_primitive_neutral_90",
"color_primitive_pink_100",
"color_primitive_pink_15",
"color_primitive_plum_100",
"color_primitive_plum_30",
"color_primitive_plum_50",
"color_primitive_plum_60",
"color_primitive_purple_30",
"color_primitive_purple_50",
"color_primitive_sky_100",
"color_primitive_sky_20",
"color_primitive_sky_25",
"color_primitive_sky_35",
"color_primitive_sky_40",
"color_primitive_sky_45",
"color_primitive_sky_55",
"color_primitive_sky_60",
"color_primitive_sky_65",
"color_primitive_sky_75",
"color_primitive_sky_80",
"color_primitive_sky_85",
"color_primitive_terracotta_30",
"color_primitive_terracotta_50",
"color_primitive_tomato_10",
"color_primitive_tomato_100",
"color_primitive_tomato_130",
"color_primitive_tomato_15",
"color_primitive_tomato_20",
"color_primitive_tomato_30",
"color_primitive_tomato_40",
"color_primitive_tomato_50",
"color_primitive_tomato_60",
"color_primitive_tomato_70",
"color_primitive_tomato_80",
"color_primitive_turquoise_30",
"color_primitive_turquoise_50",
"color_primitive_violet_30",
"color_primitive_violet_50",
"color_primitive_viridian_100",
"color_primitive_viridian_30",
"color_primitive_viridian_50",
"color_primitive_viridian_60",
"color_primitive_white",
"color_primitive_yellow_10",
"color_primitive_yellow_100",
"color_primitive_yellow_130",
"color_primitive_yellow_30",
"color_primitive_yellow_40",
"color_primitive_yellow_50",
"color_primitive_yellow_60",
"color_semantic_background_default",
"color_semantic_border_temp_tag_darkgreen",
"color_semantic_border_temp_tag_darkmarine",
"color_semantic_border_temp_tag_darkred",
"color_semantic_border_temp_tag_darkyellow",
"color_semantic_border_temp_tag_gray",
"color_semantic_border_temp_tag_green",
"color_semantic_border_temp_tag_marine",
"color_semantic_border_temp_tag_red",
"color_semantic_border_temp_tag_yellow",
"color_semantic_border_button_disabled",
"color_semantic_border_button_fill_default",
"color_semantic_border_button_fill_destructive_default",
"color_semantic_border_button_fill_destructive_focus",
"color_semantic_border_button_fill_destructive_hover",
"color_semantic_border_button_fill_focus",
"color_semantic_border_button_fill_hover",
"color_semantic_border_button_loading",
"color_semantic_border_button_outline_default",
"color_semantic_border_button_outline_destructive_default",
"color_semantic_border_button_outline_destructive_focus",
"color_semantic_border_button_outline_destructive_hover",
"color_semantic_border_button_outline_focus",
"color_semantic_border_button_outline_hover",
"color_semantic_border_button_selected",
"color_semantic_border_button_selected_hover",
"color_semantic_border_button_text_default",
"color_semantic_border_button_text_destructive_default",
"color_semantic_border_button_text_destructive_focus",
"color_semantic_border_button_text_destructive_hover",
"color_semantic_border_button_text_focus",
"color_semantic_border_button_text_hover",
"color_semantic_border_check_unchecked",
"color_semantic_border_error",
"color_semantic_border_focus",
"color_semantic_border_information",
"color_semantic_border_inverse",
"color_semantic_border_regular",
"color_semantic_border_selected",
"color_semantic_border_selected_hover",
"color_semantic_border_semi_strong",
"color_semantic_border_semi_weak",
"color_semantic_border_strong",
"color_semantic_border_success",
"color_semantic_border_warning",
"color_semantic_brand_default",
"color_semantic_chart_heatmap_1",
"color_semantic_chart_heatmap_2",
"color_semantic_chart_heatmap_3",
"color_semantic_chart_heatmap_4",
"color_semantic_chart_multi_fill_1",
"color_semantic_chart_multi_fill_10",
"color_semantic_chart_multi_fill_11",
"color_semantic_chart_multi_fill_12",
"color_semantic_chart_multi_fill_13",
"color_semantic_chart_multi_fill_14",
"color_semantic_chart_multi_fill_15",
"color_semantic_chart_multi_fill_16",
"color_semantic_chart_multi_fill_17",
"color_semantic_chart_multi_fill_18",
"color_semantic_chart_multi_fill_19",
"color_semantic_chart_multi_fill_2",
"color_semantic_chart_multi_fill_20",
"color_semantic_chart_multi_fill_21",
"color_semantic_chart_multi_fill_22",
"color_semantic_chart_multi_fill_23",
"color_semantic_chart_multi_fill_24",
"color_semantic_chart_multi_fill_25",
"color_semantic_chart_multi_fill_26",
"color_semantic_chart_multi_fill_27",
"color_semantic_chart_multi_fill_28",
"color_semantic_chart_multi_fill_29",
"color_semantic_chart_multi_fill_3",
"color_semantic_chart_multi_fill_30",
"color_semantic_chart_multi_fill_31",
"color_semantic_chart_multi_fill_32",
"color_semantic_chart_multi_fill_33",
"color_semantic_chart_multi_fill_34",
"color_semantic_chart_multi_fill_35",
"color_semantic_chart_multi_fill_36",
"color_semantic_chart_multi_fill_37",
"color_semantic_chart_multi_fill_38",
"color_semantic_chart_multi_fill_4",
"color_semantic_chart_multi_fill_5",
"color_semantic_chart_multi_fill_6",
"color_semantic_chart_multi_fill_7",
"color_semantic_chart_multi_fill_8",
"color_semantic_chart_multi_fill_9",
"color_semantic_chart_multi_line_1",
"color_semantic_chart_multi_line_10",
"color_semantic_chart_multi_line_11",
"color_semantic_chart_multi_line_12",
"color_semantic_chart_multi_line_13",
"color_semantic_chart_multi_line_14",
"color_semantic_chart_multi_line_15",
"color_semantic_chart_multi_line_16",
"color_semantic_chart_multi_line_2",
"color_semantic_chart_multi_line_3",
"color_semantic_chart_multi_line_4",
"color_semantic_chart_multi_line_5",
"color_semantic_chart_multi_line_6",
"color_semantic_chart_multi_line_7",
"color_semantic_chart_multi_line_8",
"color_semantic_chart_multi_line_9",
"color_semantic_chart_single_1",
"color_semantic_chart_single_2",
"color_semantic_chart_single_3",
"color_semantic_chart_single_4",
"color_semantic_chart_single_5",
"color_semantic_chart_single_6",
"color_semantic_chart_single_7",
"color_semantic_chart_single_8",
"color_semantic_elevation_modal",
"color_semantic_elevation_regular",
"color_semantic_elevation_sort",
"color_semantic_highlight_focus_ring_default",
"color_semantic_highlight_focus_ring_error",
"color_semantic_highlight_text",
"color_semantic_surface_temp_tag_darkgreen",
"color_semantic_surface_temp_tag_darkmarine",
"color_semantic_surface_temp_tag_darkred",
"color_semantic_surface_temp_tag_darkyellow",
"color_semantic_surface_temp_tag_gray",
"color_semantic_surface_temp_tag_green",
"color_semantic_surface_temp_tag_marine",
"color_semantic_surface_temp_tag_red",
"color_semantic_surface_temp_tag_yellow",
"color_semantic_surface_button_disabled",
"color_semantic_surface_button_fill_default",
"color_semantic_surface_button_fill_destructive_default",
"color_semantic_surface_button_fill_destructive_focus",
"color_semantic_surface_button_fill_destructive_hover",
"color_semantic_surface_button_fill_focus",
"color_semantic_surface_button_fill_hover",
"color_semantic_surface_button_loading",
"color_semantic_surface_button_outline_default",
"color_semantic_surface_button_outline_destructive_default",
"color_semantic_surface_button_outline_destructive_focus",
"color_semantic_surface_button_outline_destructive_hover",
"color_semantic_surface_button_outline_focus",
"color_semantic_surface_button_outline_hover",
"color_semantic_surface_button_selected",
"color_semantic_surface_button_selected_hover",
"color_semantic_surface_button_text_default",
"color_semantic_surface_button_text_destructive_default",
"color_semantic_surface_button_text_destructive_focus",
"color_semantic_surface_button_text_destructive_hover",
"color_semantic_surface_button_text_focus",
"color_semantic_surface_button_text_hover",
"color_semantic_surface_check_disabled",
"color_semantic_surface_checked",
"color_semantic_surface_checked_hover",
"color_semantic_surface_error_1",
"color_semantic_surface_error_3",
"color_semantic_surface_information_1",
"color_semantic_surface_information_3",
"color_semantic_surface_regular_1",
"color_semantic_surface_regular_2",
"color_semantic_surface_regular_3",
"color_semantic_surface_regular_4",
"color_semantic_surface_regular_5",
"color_semantic_surface_regular_6",
"color_semantic_surface_regular_7",
"color_semantic_surface_regular_8",
"color_semantic_surface_regular_9",
"color_semantic_surface_selected",
"color_semantic_surface_selected_focus",
"color_semantic_surface_selected_hover",
"color_semantic_surface_success_1",
"color_semantic_surface_success_3",
"color_semantic_surface_warning_1",
"color_semantic_surface_warning_3",
"color_semantic_text_button_disabled",
"color_semantic_text_button_fill_default",
"color_semantic_text_button_fill_destructive_default",
"color_semantic_text_button_fill_destructive_focus",
"color_semantic_text_button_fill_destructive_hover",
"color_semantic_text_button_fill_focus",
"color_semantic_text_button_fill_hover",
"color_semantic_text_button_loading",
"color_semantic_text_button_outline_default",
"color_semantic_text_button_outline_destructive_default",
"color_semantic_text_button_outline_destructive_focus",
"color_semantic_text_button_outline_destructive_hover",
"color_semantic_text_button_outline_focus",
"color_semantic_text_button_outline_hover",
"color_semantic_text_button_selected",
"color_semantic_text_button_selected_hover",
"color_semantic_text_button_text_default",
"color_semantic_text_button_text_destructive_default",
"color_semantic_text_button_text_destructive_focus",
"color_semantic_text_button_text_destructive_hover",
"color_semantic_text_button_text_focus",
"color_semantic_text_button_text_hover",
"color_semantic_text_current",
"color_semantic_text_destructive",
"color_semantic_text_disabled",
"color_semantic_text_error",
"color_semantic_text_inverse",
"color_semantic_text_placeholder",
"color_semantic_text_regular",
"color_semantic_text_required",
"color_semantic_text_semi_weak",
"color_semantic_text_text_link",
"color_semantic_text_weak",
"font_family_ja",
"font_family_zh",
] as const;
export type SpTokenTypes = (typeof spTokenTypes)[number];

export const tokens: {[key in SpTokenTypes]:string} = {
color_primitive_amber_30: "#e5d4c0",
color_primitive_amber_50: "#d4b797",
color_primitive_bamboo_30: "#c3daba",
color_primitive_bamboo_50: "#9bc28c",
color_primitive_blue_10: "#ecedf9",
color_primitive_blue_100: "#404fbf",
color_primitive_blue_15: "#e2e5f5",
color_primitive_blue_20: "#d9dcf2",
color_primitive_blue_30: "#c6caec",
color_primitive_blue_50: "#a0a7df",
color_primitive_blue_60: "#8c95d9",
color_primitive_blue_90: "#5361c5",
color_primitive_brown_30: "#ebcec4",
color_primitive_brown_50: "#dead9c",
color_primitive_cork_100: "#b38732",
color_primitive_cork_30: "#e8dbc2",
color_primitive_cork_50: "#d9c399",
color_primitive_cork_60: "#d1b784",
color_primitive_emerald_30: "#c0e5e3",
color_primitive_emerald_50: "#96d4d1",
color_primitive_green_10: "#e8f1eb",
color_primitive_green_100: "#1a7037",
color_primitive_green_130: "#124e27",
color_primitive_green_30: "#bad4c3",
color_primitive_green_40: "#a3c6af",
color_primitive_green_50: "#8db89b",
color_primitive_leaf_30: "#cfe1bf",
color_primitive_leaf_50: "#b0ce94",
color_primitive_lemon_30: "#f0edc1",
color_primitive_lemon_50: "#e6e197",
color_primitive_lime_100: "#a9ad2f",
color_primitive_lime_30: "#e5e6c1",
color_primitive_lime_50: "#d4d697",
color_primitive_lime_60: "#cbce82",
color_primitive_marine_10: "#ebf2f9",
color_primitive_marine_100: "#3978bf",
color_primitive_marine_130: "#285486",
color_primitive_marine_30: "#c4d7ec",
color_primitive_marine_40: "#b0c9e5",
color_primitive_marine_50: "#9cbcdf",
color_primitive_marine_60: "#88aed9",
color_primitive_neutral_10: "#f8f8f8",
color_primitive_neutral_100: "#191919",
color_primitive_neutral_20: "#f5f5f5",
color_primitive_neutral_30: "#ededed",
color_primitive_neutral_40: "#e5e5e5",
color_primitive_neutral_50: "#cbcbcb",
color_primitive_neutral_70: "#6f6f6f",
color_primitive_neutral_80: "#363636",
color_primitive_neutral_90: "#282828",
color_primitive_pink_100: "#ff5e83",
color_primitive_pink_15: "#ffe7ec",
color_primitive_plum_100: "#b3308a",
color_primitive_plum_30: "#e8c1dc",
color_primitive_plum_50: "#d998c5",
color_primitive_plum_60: "#d183b9",
color_primitive_purple_30: "#e0c5ee",
color_primitive_purple_50: "#cc9ee3",
color_primitive_sky_100: "#5c8dff",
color_primitive_sky_20: "#dee8ff",
color_primitive_sky_25: "#d6e3ff",
color_primitive_sky_35: "#c6d7ff",
color_primitive_sky_40: "#bed1ff",
color_primitive_sky_45: "#b6ccff",
color_primitive_sky_55: "#a5c0ff",
color_primitive_sky_60: "#9dbbff",
color_primitive_sky_65: "#95b5ff",
color_primitive_sky_75: "#85aaff",
color_primitive_sky_80: "#7da4ff",
color_primitive_sky_85: "#749eff",
color_primitive_terracotta_30: "#edc6c1",
color_primitive_terracotta_50: "#e1a098",
color_primitive_tomato_10: "#faebeb",
color_primitive_tomato_100: "#ca3232",
color_primitive_tomato_130: "#8d2323",
color_primitive_tomato_15: "#f7e0e0",
color_primitive_tomato_20: "#f4d6d6",
color_primitive_tomato_30: "#efc2c2",
color_primitive_tomato_40: "#eaadad",
color_primitive_tomato_50: "#e59999",
color_primitive_tomato_60: "#df8484",
color_primitive_tomato_70: "#da7070",
color_primitive_tomato_80: "#d55b5b",
color_primitive_turquoise_30: "#bedbe2",
color_primitive_turquoise_50: "#93c4cf",
color_primitive_violet_30: "#d1c5e8",
color_primitive_violet_50: "#b29ed9",
color_primitive_viridian_100: "#248a6a",
color_primitive_viridian_30: "#bddcd2",
color_primitive_viridian_50: "#92c5b5",
color_primitive_viridian_60: "#7cb9a6",
color_primitive_white: "#ffffff",
color_primitive_yellow_10: "#fdf7e6",
color_primitive_yellow_100: "#eab100",
color_primitive_yellow_130: "#a47c00",
color_primitive_yellow_30: "#f9e8b3",
color_primitive_yellow_40: "#f7e099",
color_primitive_yellow_50: "#f5d880",
color_primitive_yellow_60: "#f2d066",
color_semantic_background_default: "#f8f8f8",
color_semantic_border_temp_tag_darkgreen: "#124e27",
color_semantic_border_temp_tag_darkmarine: "#285486",
color_semantic_border_temp_tag_darkred: "#8d2323",
color_semantic_border_temp_tag_darkyellow: "#a47c00",
color_semantic_border_temp_tag_gray: "#e5e5e5",
color_semantic_border_temp_tag_green: "#a3c6af",
color_semantic_border_temp_tag_marine: "#b0c9e5",
color_semantic_border_temp_tag_red: "#eaadad",
color_semantic_border_temp_tag_yellow: "#f7e099",
color_semantic_border_button_disabled: "#e5e5e5",
color_semantic_border_button_fill_default: "#191919",
color_semantic_border_button_fill_destructive_default: "#ca3232",
color_semantic_border_button_fill_destructive_focus: "#d55b5b",
color_semantic_border_button_fill_destructive_hover: "#d55b5b",
color_semantic_border_button_fill_focus: "#363636",
color_semantic_border_button_fill_hover: "#363636",
color_semantic_border_button_loading: "#e5e5e5",
color_semantic_border_button_outline_default: "#191919",
color_semantic_border_button_outline_destructive_default: "#ca3232",
color_semantic_border_button_outline_destructive_focus: "#da7070",
color_semantic_border_button_outline_destructive_hover: "#da7070",
color_semantic_border_button_outline_focus: "#6f6f6f",
color_semantic_border_button_outline_hover: "#6f6f6f",
color_semantic_border_button_selected: "#404fbf",
color_semantic_border_button_selected_hover: "#5361c5",
color_semantic_border_button_text_default: "#19191900",
color_semantic_border_button_text_destructive_default: "#ca323200",
color_semantic_border_button_text_destructive_focus: "#f4d6d6",
color_semantic_border_button_text_destructive_hover: "#f4d6d6",
color_semantic_border_button_text_focus: "#f5f5f5",
color_semantic_border_button_text_hover: "#f5f5f5",
color_semantic_border_check_unchecked: "#cbcbcb",
color_semantic_border_error: "#ca3232",
color_semantic_border_focus: "#404fbf",
color_semantic_border_information: "#3978bf",
color_semantic_border_inverse: "#ffffff",
color_semantic_border_regular: "#e5e5e5",
color_semantic_border_selected: "#404fbf",
color_semantic_border_selected_hover: "#5361c5",
color_semantic_border_semi_strong: "#363636",
color_semantic_border_semi_weak: "#ededed",
color_semantic_border_strong: "#191919",
color_semantic_border_success: "#1a7037",
color_semantic_border_warning: "#eab100",
color_semantic_brand_default: "#ff5e83",
color_semantic_chart_heatmap_1: "#7da4ff",
color_semantic_chart_heatmap_2: "#9dbbff",
color_semantic_chart_heatmap_3: "#bed1ff",
color_semantic_chart_heatmap_4: "#dee8ff",
color_semantic_chart_multi_fill_1: "#9cbcdf",
color_semantic_chart_multi_fill_10: "#a0a7df",
color_semantic_chart_multi_fill_11: "#93c4cf",
color_semantic_chart_multi_fill_12: "#92c5b5",
color_semantic_chart_multi_fill_13: "#9bc28c",
color_semantic_chart_multi_fill_14: "#d4d697",
color_semantic_chart_multi_fill_15: "#f5d880",
color_semantic_chart_multi_fill_16: "#d4b797",
color_semantic_chart_multi_fill_17: "#e1a098",
color_semantic_chart_multi_fill_18: "#d998c5",
color_semantic_chart_multi_fill_19: "#b29ed9",
color_semantic_chart_multi_fill_2: "#96d4d1",
color_semantic_chart_multi_fill_20: "#c4d7ec",
color_semantic_chart_multi_fill_21: "#c0e5e3",
color_semantic_chart_multi_fill_22: "#bad4c3",
color_semantic_chart_multi_fill_23: "#cfe1bf",
color_semantic_chart_multi_fill_24: "#f0edc1",
color_semantic_chart_multi_fill_25: "#e8dbc2",
color_semantic_chart_multi_fill_26: "#ebcec4",
color_semantic_chart_multi_fill_27: "#efc2c2",
color_semantic_chart_multi_fill_28: "#e0c5ee",
color_semantic_chart_multi_fill_29: "#c6caec",
color_semantic_chart_multi_fill_3: "#8db89b",
color_semantic_chart_multi_fill_30: "#bedbe2",
color_semantic_chart_multi_fill_31: "#bddcd2",
color_semantic_chart_multi_fill_32: "#c3daba",
color_semantic_chart_multi_fill_33: "#e5e6c1",
color_semantic_chart_multi_fill_34: "#f9e8b3",
color_semantic_chart_multi_fill_35: "#e5d4c0",
color_semantic_chart_multi_fill_36: "#edc6c1",
color_semantic_chart_multi_fill_37: "#e8c1dc",
color_semantic_chart_multi_fill_38: "#d1c5e8",
color_semantic_chart_multi_fill_4: "#b0ce94",
color_semantic_chart_multi_fill_5: "#e6e197",
color_semantic_chart_multi_fill_6: "#d9c399",
color_semantic_chart_multi_fill_7: "#dead9c",
color_semantic_chart_multi_fill_8: "#e59999",
color_semantic_chart_multi_fill_9: "#cc9ee3",
color_semantic_chart_multi_line_1: "#ca3232",
color_semantic_chart_multi_line_10: "#d1b784",
color_semantic_chart_multi_line_11: "#f2d066",
color_semantic_chart_multi_line_12: "#cbce82",
color_semantic_chart_multi_line_13: "#7cb9a6",
color_semantic_chart_multi_line_14: "#88aed9",
color_semantic_chart_multi_line_15: "#8c95d9",
color_semantic_chart_multi_line_16: "#d183b9",
color_semantic_chart_multi_line_2: "#b38732",
color_semantic_chart_multi_line_3: "#eab100",
color_semantic_chart_multi_line_4: "#a9ad2f",
color_semantic_chart_multi_line_5: "#248a6a",
color_semantic_chart_multi_line_6: "#3978bf",
color_semantic_chart_multi_line_7: "#404fbf",
color_semantic_chart_multi_line_8: "#b3308a",
color_semantic_chart_multi_line_9: "#df8484",
color_semantic_chart_single_1: "#5c8dff",
color_semantic_chart_single_2: "#749eff",
color_semantic_chart_single_3: "#85aaff",
color_semantic_chart_single_4: "#95b5ff",
color_semantic_chart_single_5: "#a5c0ff",
color_semantic_chart_single_6: "#b6ccff",
color_semantic_chart_single_7: "#c6d7ff",
color_semantic_chart_single_8: "#d6e3ff",
color_semantic_elevation_modal: "#19191933",
color_semantic_elevation_regular: "#19191933",
color_semantic_elevation_sort: "#19191933",
color_semantic_highlight_focus_ring_default: "#e2e5f5",
color_semantic_highlight_focus_ring_error: "#f7e0e0",
color_semantic_highlight_text: "#ffe7ec",
color_semantic_surface_temp_tag_darkgreen: "#1a7037",
color_semantic_surface_temp_tag_darkmarine: "#3978bf",
color_semantic_surface_temp_tag_darkred: "#ca3232",
color_semantic_surface_temp_tag_darkyellow: "#eab100",
color_semantic_surface_temp_tag_gray: "#f8f8f8",
color_semantic_surface_temp_tag_green: "#e8f1eb",
color_semantic_surface_temp_tag_marine: "#ebf2f9",
color_semantic_surface_temp_tag_red: "#faebeb",
color_semantic_surface_temp_tag_yellow: "#fdf7e6",
color_semantic_surface_button_disabled: "#f8f8f8",
color_semantic_surface_button_fill_default: "#191919",
color_semantic_surface_button_fill_destructive_default: "#ca3232",
color_semantic_surface_button_fill_destructive_focus: "#d55b5b",
color_semantic_surface_button_fill_destructive_hover: "#d55b5b",
color_semantic_surface_button_fill_focus: "#363636",
color_semantic_surface_button_fill_hover: "#363636",
color_semantic_surface_button_loading: "#f8f8f8",
color_semantic_surface_button_outline_default: "#19191900",
color_semantic_surface_button_outline_destructive_default: "#ca323200",
color_semantic_surface_button_outline_destructive_focus: "#da707000",
color_semantic_surface_button_outline_destructive_hover: "#da707000",
color_semantic_surface_button_outline_focus: "#19191900",
color_semantic_surface_button_outline_hover: "#19191900",
color_semantic_surface_button_selected: "#404fbf",
color_semantic_surface_button_selected_hover: "#5361c5",
color_semantic_surface_button_text_default: "#19191900",
color_semantic_surface_button_text_destructive_default: "#ca323200",
color_semantic_surface_button_text_destructive_focus: "#f4d6d6",
color_semantic_surface_button_text_destructive_hover: "#f4d6d6",
color_semantic_surface_button_text_focus: "#f5f5f5",
color_semantic_surface_button_text_hover: "#f5f5f5",
color_semantic_surface_check_disabled: "#ededed",
color_semantic_surface_checked: "#ecedf9",
color_semantic_surface_checked_hover: "#d9dcf2",
color_semantic_surface_error_1: "#faebeb",
color_semantic_surface_error_3: "#efc2c2",
color_semantic_surface_information_1: "#ebf2f9",
color_semantic_surface_information_3: "#c4d7ec",
color_semantic_surface_regular_1: "#ffffff",
color_semantic_surface_regular_2: "#f8f8f8",
color_semantic_surface_regular_3: "#f5f5f5",
color_semantic_surface_regular_4: "#ededed",
color_semantic_surface_regular_5: "#e5e5e5",
color_semantic_surface_regular_6: "#cbcbcb",
color_semantic_surface_regular_7: "#363636",
color_semantic_surface_regular_8: "#282828",
color_semantic_surface_regular_9: "#191919",
color_semantic_surface_selected: "#404fbf",
color_semantic_surface_selected_focus: "#404fbf",
color_semantic_surface_selected_hover: "#5361c5",
color_semantic_surface_success_1: "#e8f1eb",
color_semantic_surface_success_3: "#bad4c3",
color_semantic_surface_warning_1: "#fdf7e6",
color_semantic_surface_warning_3: "#f9e8b3",
color_semantic_text_button_disabled: "#cbcbcb",
color_semantic_text_button_fill_default: "#ffffff",
color_semantic_text_button_fill_destructive_default: "#ffffff",
color_semantic_text_button_fill_destructive_focus: "#ffffff",
color_semantic_text_button_fill_destructive_hover: "#ffffff",
color_semantic_text_button_fill_focus: "#ffffff",
color_semantic_text_button_fill_hover: "#ffffff",
color_semantic_text_button_loading: "#cbcbcb",
color_semantic_text_button_outline_default: "#191919",
color_semantic_text_button_outline_destructive_default: "#ca3232",
color_semantic_text_button_outline_destructive_focus: "#da7070",
color_semantic_text_button_outline_destructive_hover: "#da7070",
color_semantic_text_button_outline_focus: "#6f6f6f",
color_semantic_text_button_outline_hover: "#6f6f6f",
color_semantic_text_button_selected: "#ffffff",
color_semantic_text_button_selected_hover: "#ffffff",
color_semantic_text_button_text_default: "#191919",
color_semantic_text_button_text_destructive_default: "#ca3232",
color_semantic_text_button_text_destructive_focus: "#ca3232",
color_semantic_text_button_text_destructive_hover: "#ca3232",
color_semantic_text_button_text_focus: "#191919",
color_semantic_text_button_text_hover: "#191919",
color_semantic_text_current: "#404fbf",
color_semantic_text_destructive: "#ca3232",
color_semantic_text_disabled: "#cbcbcb",
color_semantic_text_error: "#ca3232",
color_semantic_text_inverse: "#ffffff",
color_semantic_text_placeholder: "#6f6f6f",
color_semantic_text_regular: "#191919",
color_semantic_text_required: "#ca3232",
color_semantic_text_semi_weak: "#363636",
color_semantic_text_text_link: "#404fbf",
color_semantic_text_weak: "#6f6f6f",
font_family_ja: "Arial, YakuHanJPs, Hiragino Sans, Hiragino Kaku Gothic ProN, Meiryo, Noto Sans JP, sans-serif",
font_family_zh: "Arial, YakuHanJPs, 'PingFang SC', 'Microsoft YaHei', 'PingFang TC', Microsoft JhengHei, sans-serif",
}